## Using docker compose to create multi container docker application, one running DB, another running the .NET API application
## Not tested

version: "3.8"
services:
    web:
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
            - "0.0.0.0:8000:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        env_file: 
        - dbconf.env
        ports:
            - "1433:1433"

networks:
  default:
    external:
      name: my-network
