apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nathmahale/homelabzz.git
    targetRevision: develop
    path: kubernetes/argocd/calico-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
