apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jdemo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nathmahale/homelabzz.git
    targetRevision: develop
    path: kubernetes/argocd/jdemo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: jdemo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
