apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nathmahale/argocd.git
    targetRevision: develop
    path: prometheus-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
